# Enable I2C support
CONFIG_I2C=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
# CONFIG_NET_SOCKETS_POSIX_NAMES=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y

CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_DHCPV4=y

CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_MAIN_STACK_SIZE=10240
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=65536

CONFIG_LOG=n
CONFIG_PRINTK=y

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y

CONFIG_NET_SHELL=y
CONFIG_NET_L2_WIFI_SHELL=y
